/mavros:
  ros__parameters:
    plugin_blacklist:
      # common

      # extras
      - image_pub
      - vibration
      - distance_sensor
      - rangefinder
      - wheel_odometry
    plugin_whitelist:
      []
      # - 'sys_*'
